development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: nuit2011_development
  pool: 5
  username: admin
  password: password

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: nuit2011_test
  pool: 5
  username: admin
  password: password

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: nuit2011_production
  pool: 5
  username: admin
  password: password